input {
  tcp {
    port => ${LOGSTASH_PORT:5000}
    codec => json
  }

  udp {
    port => ${LOGSTASH_PORT:5000}
    codec => json
  }

  beats {
    port => 5044
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://${ELASTIC_HOST:localhost}:${ELASTIC_PORT:9200}"]
    index => "logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}