services:

  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak
    command: start-dev
    depends_on:
      - db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "9090:8080"

  identity_backend:
    build:
      context: .
      dockerfile: ./identity_service/Dockerfile
    container_name: identity_backend
    restart: always
    depends_on:
      - db
      - keycloak
    ports:
      - "8080:8081"
    env_file:
      - .env
volumes:
  postgres_data:
  