version: "3.9"

services:

  postgres:
    image: postgres:18
    container_name: identity_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spring_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DATABASE}
      SPRING_DATASOURCE_USERNAME: ${USER}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}

volumes:
  postgres_data: