spring:
  application:
    name: feed-service
server:
  port: 8084

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics

info:
  app:
    name: Feed service
    description: Post management and comment creating service