spring:
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: identity_service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
          jwks-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}/realms/modsen-social/protocol/openid-connect/certs

keycloak:
  server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}
  realm: modsen-social
  client-id: api-gateway
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  username: ${KEYCLOAK_ADMIN}
  password: ${KEYCLOAK_ADMIN_PASSWORD}

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8082

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics  

info:
  app:
    name: Identity service
    description: Authentication and authorize service
