spring:
  application:
    name: api-gateway
  grpc:
    client:
      default-channel:
        address: static://${IDENTITY_CONTAINER_NAME:localhost}:9090
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

server:
  port: 8081

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics  

info:
  app:
    name: API Gateway
    description: Single entrypoint

logging:
  aspect:
    include:
    - "* com.kolmir.api_gateway.service..*(..)"
    exclude: []
